### ISSUE TITLE
Неточности верстки

### ISSUE THREAD

**Issue by OlgaYubil** [victordesyatkin/toxin#15]
![2021-05-09_01-10-14](https://user-images.githubusercontent.com/82147736/117569515-be74a880-b0ce-11eb-9ccc-d9042e992155.png)

Тень слишком яркая

![2021-05-09_14-00-03](https://user-images.githubusercontent.com/82147736/117569566-f4199180-b0ce-11eb-91c8-5c4f641585f5.png)

**Comment by OlgaYubil** [comment]
Мне кажется, группа чекбоксов это все же не article
![2021-05-09_02-09-53](https://user-images.githubusercontent.com/82147736/117569868-52933f80-b0d0-11eb-9e26-2d29883de473.png)

**Comment by victordesyatkin** [comment]
По спецификации https://html.spec.whatwg.org/dev/sections.html#the-article-element, article - это "... интерактивный виджет или гаджет или любой другой независимый элемент контента". Объясните почему компонент checkbox-buttons или группа checkboxes это не article (у компонента есть свой собственный заголовок и он может быть использован как независимый элемент контента на любой странице или в любой ее части)?
