### ISSUE TITLE
Верстка

### ISSUE THREAD

**Issue by Yubil-Olga** [victordesyatkin/toxin#2]
При изменении масштаба фон не растягивается
![2021-04-11_21-47-52](https://user-images.githubusercontent.com/47268368/114318853-8ef66e80-9b17-11eb-81f1-a9fd4118fa2c.png)

**Comment by Yubil-Olga** [comment]
На странице room-details like-button можно нажать, но счетчик не меняется. А на странице search-room-filter rate-button имеет курсор pointer, но нажать нельзя.

**Comment by OlgaYubil** [comment]
Можно закрыть
