### ISSUE TITLE
Компоненты

### ISSUE THREAD

**Issue by Yubil-Olga** [victordesyatkin/toxin#3]
У некоторых компонентов отсутствуют pug-файлы. Это нарушает его самодостаточность.

**Comment by OlgaYubil** [comment]
Не все исправил, например air-datepicker

**Comment by OlgaYubil** [comment]
Пустые файлы стилей и скриптов нужно убрать

**Comment by OlgaYubil** [comment]
Сейчас в компоненте layout лежит несколько миксинов, но так быть не должно. Один компонент - один миксин.

**Comment by OlgaYubil** [comment]
Можно закрыть
