### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by Yubil-Olga** [victordesyatkin/toxin#4]
Мне кажется, здесь теряется смысл вынесения цветов в переменную, очень много дублирования.

![2021-04-11_23-07-46](https://user-images.githubusercontent.com/47268368/114319668-172a4300-9b1b-11eb-80c8-bfb6c9fdd04b.png)

**Comment by OlgaYubil** [comment]
Переменных слишком много, они должны помогать, а не усложнять поддержку кода. Хорошо, если названия будут осмысленные. Цвет номер пять, например, не особо информативное наименование
![2021-04-16_23-31-23](https://user-images.githubusercontent.com/82147736/115081231-9b5e3b00-9f0c-11eb-8c1d-3f539ee72eb0.png)

**Comment by OlgaYubil** [comment]
Можно закрыть
