### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by Yubil-Olga** [victordesyatkin/toxin#5]
Поправить отступы
![2021-04-11_23-13-06](https://user-images.githubusercontent.com/47268368/114319797-b0595980-9b1b-11eb-8881-6a7f771f8c53.png)

**Comment by OlgaYubil** [comment]
Остались еще неисправленные места, например в book.pug

**Comment by OlgaYubil** [comment]
Если у элемента блока есть модификаторы или, например, псевдоэлементы, то css-стили нужно сделать вложенными:
![2021-04-20_20-50-53](https://user-images.githubusercontent.com/82147736/115442218-6e669c80-a21a-11eb-976d-5f21d7e51475.png)

**Comment by OlgaYubil** [comment]
Можно закрыть

**Comment by OlgaYubil** [comment]
Удалить из кода комментарии

**Comment by OlgaYubil** [comment]
Можно закрыть
